### PR TITLE
Semi-Auto Incentive Adjust - Prop 13

### PR DESCRIPTION
**Pull request by UnityChaos**
WIP Draft of an idea discussed in the Osmosis Discord.

Feedback on the Meta-Proposal, Model, Algorithm, etc. would be highly appreciated.

If the general consensus here and on Discord is that this is a reasonable way to proceed, then I will propose the final draft as a Text proposal on Osmosis, and create a corresponding parameter change proposal to implement the first adjustment. Given that Prop 9 passed July 7th at 7:30pm UTC, and the first payout effected by it was on the 9th, it would make sense to delay any adjustment proposal until at least the 16th.

### CODE REVIEW

**Comment by cosmonought** [comment]
Hello! I don't know if this is where to post this, but I'm just wondering if there is a "Reader's Digest" version of the incentive adjustment mechanism that can be reviewed? I looked at the long-form proposal document but don't have time to sit with it before the vote (and this stuff is not really my 'field'), so instead I'm hoping for some 2-3 sentence summary explanation like: Every 7 days, incentives to pools will be adjusted by up to 10% based on the OSMO Bias, which is calculated by dividing the X by Y; or whatever the accurate summary is. Thank you for your help!

**Comment by Philinje** [comment]
Yes, the summary would help, and then moving the whole discussion to Discourse where individual points can be discussed would be helpful. Does Osmosis have a Discourse forum?

**Comment by UnityChaos** [comment]
> 
> 
> Hello! I don't know if this is where to post this, but I'm just wondering if there is a "Reader's Digest" version of the incentive adjustment mechanism that can be reviewed? I looked at the long-form proposal document but don't have time to sit with it before the vote (and this stuff is not really my 'field'), so instead I'm hoping for some 2-3 sentence summary explanation like: Every 7 days, incentives to pools will be adjusted by up to 10% based on the OSMO Bias, which is calculated by dividing the X by Y; or whatever the accurate summary is. Thank you for your help!


Okay, TLDR description:
- We want pools to be liquid to facilitate trading.
- Highly liquid pools with little volume are too liquid
- Low liquidity pools with high volume are not liquid enough.
- To represent this we compare total value locked in the pool with the volume transacted through the pool in the last week to get the "relative liquidity"
- To give an advantage to Osmo pools, we treat them as having less liquidity than they do, and Atom pools as having more.
- Then we adjust the incentives of each pool, by no more than 10%, to push them all towards the average level of relative liquidity. So Those with low relative liquidity get more share of incentives, those with high relative liquidity get less.

Proposal says to repeat this every 2 weeks, so we can see the effects of the previous adjustment before starting the next one. (But @ValarDragon has recommended we run weekly at the start to accelerate the early changes)

**Comment by cosmonought** [comment]
Super helpful! Thank you!

**Pull request merged**
